#!/bin/sh

# PROVIDE: milter-manager
# REQUIRE: LOGIN
# BEFORE: mail
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf to enable milter-manager:
#
#   milter_manager_enable=yes
#

. /etc/rc.subr

name="milter_manager"
rcvar=`set_rcvar`

command=/usr/local/bin/milter-manager

load_rc_config $name
: ${milter_manager_enable="NO"}

run_rc_command "$1"
