FROM centos:7

RUN yum update -y && \
    yum install -y \
      libtool intltool gettext gcc make glib2-devel git tar rpm-build \
      ruby ruby-devel rubygems lcov rsyslog sudo git epel-release && \
    yum install -y  http://sourceforge.net/projects/cutter/files/centos/cutter-release-1.3.0-1.noarch.rpm && \
    yum makecache && \
    yum install -y lcov && \
    yum install -y cutter && \
    gem install --no-rdoc --no-ri coveralls-lcov && \
    gem install --no-rdoc --no-ri pkg-config && \
    useradd -m --user-group --shell /bin/bash milter-manager

WORKDIR /home/milter-manager/milter-manager
COPY . .
RUN chown -R milter-manager:milter-manager .
USER milter-manager
