FROM centos:6

RUN yum update -y && \
    yum install -q -y \
      libtool intltool gettext gcc make glib2-devel git tar rpm-build \
      lcov rsyslog sudo git epel-release gtk-doc \
      readline-devel ncurses-devel gdbm-devel tcl-devel openssl-devel db4-devel \
      libyaml libyaml-devel libffi-devel byacc \
      wget pyliblzma rrdtool
RUN yum install -q -y http://sourceforge.net/projects/cutter/files/centos/cutter-release-1.3.0-1.noarch.rpm && \
    yum makecache && \
    yum install -q -y lcov && \
    yum install -q -y cutter && \
    useradd -m --user-group --shell /bin/bash milter-manager

COPY ./package/yum/vendor/ruby23.spec /tmp/

RUN mkdir -p ~/rpmbuild/SOURCES ~/rpmbuild/SPECS && \
    wget --quiet http://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.5.tar.gz -P ~/rpmbuild/SOURCES && \
    rpmbuild --quiet -ba /tmp/ruby23.spec && \
    yum install -q -y ~/rpmbuild/RPMS/*/*.rpm

RUN gem2.3 install --no-rdoc --no-ri coveralls-lcov pkg-config test-unit-rr


WORKDIR /home/milter-manager/milter-manager
COPY . .
RUN chown -R milter-manager:milter-manager .
USER milter-manager
