#!/usr/bin/env ruby
#
# Copyright (C) 2008  Kouhei Sutou <kou@cozmixng.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

require 'pathname'
require 'fileutils'
require 'time'
require 'optparse'

base = Pathname.new(__FILE__).dirname.expand_path
top = (base + "..").expand_path
$LOAD_PATH.unshift((top + "tool" + "ruby").to_s) #FIX Path
require 'milter-rrd'

class MilterLogTool
  def initialize
    @log = ARGF
    @update_db = true
    @sessions = nil
    @mail_status = nil
    @pass_child = nil
  end

  def parse_options(argv)
    opts = OptionParser.new do |opts|
      opts.on("--log=LOG_FILENAME",
              "The log file name in which is stored Milter log",
              "(STDIN)") do |log|
        @log = File.open(log)
      end

      opts.on("--rrd-directory=DIRECTORY") do |directory|
        @rrd_directory = directory
        FileUtils.mkdir_p(@rrd_directory) unless File.exist?(@rrd_directory)
      end

      opts.on("--[no-]update-db",
              "Update RRD database with log file",
              "(#{@update_db})") do |boolean|
        @update_db = boolean
      end
    end
    opts.parse!(argv)
  end

  def update
    return unless @update_db

    listeners = [sessions, mail_status, pass_child]
    @log.each_line do |line|
      listeners.each do |listener|
        listener.feed(line)
      end
    end

    listeners.each do |listener|
      listener.update
    end
  end

  def output_graph(time_span)
    sessions.output_graph(Milter::RRD::TimeSpan.new(time_span))
    mail_status.output_graph(Milter::RRD::TimeSpan.new(time_span))
    pass_child.output_graph(Milter::RRD::TimeSpan.new(time_span))
  end

  def output_all_graph
    output_graph("second")
    output_graph("minute")
    output_graph("hour")
  end

  private
  def now
    @now ||= Time.now.utc
  end

  def sessions
    @sessions ||= Milter::RRD::Session.new(@rrd_directory, now)
  end

  def mail_status
    @mail_status ||= Milter::RRD::MailStatus.new(@rrd_directory, now)
  end

  def pass_child
    @pass_child ||= Milter::RRD::PassChild.new(@rrd_directory, now)
  end
end

milter_log_tool = MilterLogTool.new
milter_log_tool.parse_options(ARGV)
milter_log_tool.update
milter_log_tool.output_all_graph

# vi:ts=2:nowrap:ai:expandtab:sw=2
