#! /bin/bash

test -f /lib/svc/share/smf_include.sh && . /lib/svc/share/smf_include.sh

MANIFEST=$BASEDIR/var/svc/manifest/network/milter-manager.xml

if smf_present && `svccfg validate $MANIFEST`; then
    svccfg import $MANIFEST
fi
exit 0
