all:
	@cd src; $(MAKE) all

install:
	@cd src; $(MAKE) install

site-install:
	@cd src; $(MAKE) site-install

clean:
	@cd src; $(MAKE) clean

distclean: clean
	@cd src; $(MAKE) distclean
	@rm -f Makefile extconf.h conftest.*
	@rm -f core *~ mkmf.log
