#!/sbin/sh

case "$1" in
'start')
        /usr/sbin/svcadm enable -t svc:/network/milter-manager
        ;;
'restart')
        /usr/sbin/svcadm restart svc:/network/milter-manager
        ;;
'stop')
        /usr/sbin/svcadm disable -t svc:/network/milter-manager
        ;;
*)
        echo "Usage: $0 { start | stop | restart }"
        exit 1
        ;;
esac
exit 0
